### ISSUE TITLE
prediction error

### ISSUE THREAD

**Issue by hujingchu** [samsledje/D-SCRIPT#29]
Hello,
Thank you for useful tool and detailed document.
I run the prediction based on the human model downloaded from https://d-script.readthedocs.io/en/main/data.html, paired file and fasta files were from github and get error below:
`Making Predictions...
  0%|                                                                                                                                                                           | 0/6 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/siat/hujc/anaconda3/envs/dscript/bin/dscript", line 8, in <module>
    sys.exit(main())
  File "/siat/hujc/anaconda3/envs/dscript/lib/python3.7/site-packages/dscript/__main__.py", line 56, in main
    args.func(args)
  File "/siat/hujc/anaconda3/envs/dscript/lib/python3.7/site-packages/dscript/commands/predict.py", line 160, in main
    cm, p = model.map_predict(p0, p1)
  File "/siat/hujc/anaconda3/envs/dscript/lib/python3.7/site-packages/dscript/models/interaction.py", line 171, in map_predict
    if self.do_w:
  File "/siat/hujc/anaconda3/envs/dscript/lib/python3.7/site-packages/torch/nn/modules/module.py", line 779, in __getattr__
    type(self).__name__, name))
torch.nn.modules.module.ModuleAttributeError: 'ModelInteraction' object has no attribute 'do_w'`
Both 1.5 and 1.7 pytorch have been tried, however, still got the same error, could you please help figure out?

**Comment by hujingchu** [comment]
Installation was following the instruction via conda and pip installation, the command line is below:
`dscript predict --pairs human_test.tsv --seqs human.fasta  --model human_v1.sav -o pred.res.txt`
human_test.tsv was truncated into 10 lines.

**Comment by samsledje** [comment]
Hi hujingchu,

Thanks for bringing this to my attention. For the short term if you want to make predictions, you can try reverting to version 0.1.6, or submit your pairs at our online prediction server (still in development, but should work) -- http://dscript-predict.csail.mit.edu.

For the long term, I'll work on fixing this ASAP. Thanks again for finding this.

**Comment by samsledje** [comment]
Hi hujingchu,

Please try re-downloading the human pretrained model from [here](http://cb.csail.mit.edu/cb/dscript/data/models/human_v1.sav). This _should_ work for you, please let me know ASAP if it doesn't!

**Comment by hujingchu** [comment]
Hi Samuel Sledzieski,
Thank you so much, it works well with version 0.1.6, however, the prediction seems a bit strange, as you can see the result below(top 6 line of the human_test.tsv), only one was higher than 0.5 (predicted to  be interacted) same result with the online version which all of them should be interact.
`9606.ENSP00000397912	9606.ENSP00000389381	0.08798135071992874
9606.ENSP00000265339	9606.ENSP00000293968	0.945186972618103
9606.ENSP00000259727	9606.ENSP00000419851	0.0768529623746872
9606.ENSP00000480334	9606.ENSP00000395401	0.01999051310122013
9606.ENSP00000225728	9606.ENSP00000255764	0.14016972482204437
9606.ENSP00000345963	9606.ENSP00000478877	0.3611184358596802`
Default parameter was used, does anything I missed?

**Comment by hujingchu** [comment]
Hi，
After came across the #25 issue, I understand , you can close this issue, thank you again
